# baseURL: 'https://pcsx2.net/'
disableKinds:
  - "taxonomy"
ignoreErrors:
  - "error-disable-taxonomy"
languageCode: en-us
title: PCSX2
theme:
  - pcsx2
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
enableEmoji: true
params:
  author: John Doe
  description: John Doe's personal website
  favicon_32: /img/favicon-32x32.png
  keywords: 'blog,developer,personal'
  info:
    - Full Stack DevOps
    - Magician
  avatarURL: images/avatar.jpg
  footerContent: ''
  dateFormat: 'January 2, 2006'
  hideFooter: false
  hideCredits: false
  hideCopyright: false
  since: 2019
  rtl: false
  colorScheme: auto
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  enableTwemoji: false
  customCSS:
    - css/custom.css
  customSCSS: []
  customJS: []
  csp:
    childsrc:
      - '''self'''
    fontsrc:
      - '''self'''
      - 'https://fonts.gstatic.com'
      - 'https://cdn.jsdelivr.net/'
    formaction:
      - '''self'''
    framesrc:
      - '''self'''
    imgsrc:
      - '''self'''
    objectsrc:
      - '''none'''
    stylesrc:
      - '''self'''
      - '''unsafe-inline'''
      - 'https://fonts.googleapis.com/'
      - 'https://cdn.jsdelivr.net/'
    scriptsrc:
      - '''self'''
      - '''unsafe-inline'''
      - 'https://www.google-analytics.com'
    prefetchsrc:
      - '''self'''
    connectsrc:
      - '''self'''
      - 'https://www.google-analytics.com'
  social:
    - name: Github
      icon: fa fa-github
      weight: 1
      url: 'https://github.com/johndoe/'
    - name: Gitlab
      icon: fa fa-gitlab
      weight: 2
      url: 'https://gitlab.com/johndoe/'
    - name: Twitter
      icon: fa fa-twitter
      weight: 3
      url: 'https://twitter.com/johndoe/'
    - name: LinkedIn
      icon: fa fa-linkedin
      weight: 4
      url: 'https://www.linkedin.com/in/johndoe/'
    - name: Medium
      icon: fa fa-medium
      weight: 5
      url: 'https://medium.com/@johndoe'
    - name: RSS
      icon: fa fa-rss
      weight: 6
      url: 'https://myhugosite.com/index.xml'
      rel: alternate
      type: application/rss+xml
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  en:
    # baseURL: 'https://pcsx2.net/en/'
    languageName: ':uk:'
    menu:
      main:
        - name: Download
          title: Downloads
          weight: 1
          url: /downloads
        - name: Compatibility
          title: Compatibility List
          weight: 2
          url: /compat
        - name: Blog
          title: Dev Blog
          weight: 3
          url: /blog
        - name: Documentation
          title: Documentation
          weight: 4
          url: /docs
        - name: About
          title: About the Project
          weight: 5
          url: /about
        - name: Discord
          weight: 6
          url: 'https://discord.com/invite/TCz3t9k'
          pre: fa fa-discord
        - name: Github
          weight: 7
          url: 'https://github.com/PCSX2/pcsx2'
          pre: fa fa-github
  # fr:
  #   baseURL: 'https://pcsx2.net/fr/'
  #   languageName: ':fr:'
  #   menu:
  #     main:
  #       - name: Télécharger
  #         title: Téléchargements
  #         weight: 1
  #         url: /downloads
  #       - name: Compatibilité
  #         title: Liste de compatibilité
  #         weight: 2
  #         url: /compat
  #       - name: Blog
  #         title: Dev Blog
  #         weight: 3
  #         url: /blog
  #       - name: Documentation
  #         title: Documentation
  #         weight: 4
  #         url: /docs
  #       - name: À propos
  #         title: À propos du projet
  #         weight: 5
  #         url: /about
  #       - name: Discord
  #         weight: 6
  #         url: 'https://discord.com/invite/TCz3t9k'
  #         pre: fa fa-discord
  #       - name: Github
  #         weight: 7
  #         url: 'https://github.com/PCSX2/pcsx2'
  #         pre: fa fa-github
